apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: pdweb-postgres:5432
    user: pdweb
    secureJsonData:
      password: pdweb
    uid: timescaledb
    jsonData:
      database: pdweb
      sslmode: 'disable'
      postgresVersion: 1400
      timescaledb: true
    isDefault: true
